language: java
sudo: required
install:
   - sudo apt-get install --yes doxygen graphviz
script: 
   - jdk_switcher use oraclejdk8
   - mvn test
   - doxygen Doxyfile
jdk: oraclejdk8
notifications:
  email: alu0100697315@ull.edu.es