language: java
sudo: required
script: 
   - jdk_switcher use oraclejdk8
   - mvn test
   - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
   - doxygen Doxyfile
jdk: oraclejdk8
notifications:
  email: alu0100697315@ull.edu.es